name: CI End-to-end tests
on: [deployment_status]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run with env
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
